uint8 START=1
uint8 STOP=2
uint8 CANCEL=3

uint8 command
string mission_id
geometry_msgs/PoseStamped target_pose
string constraints_json
uint8 priority
float32 timeout_sec
---
bool accepted
uint16 error_code
string message
---
string phase
float32 progress
